apiVersion: v1
kind: Service
metadata:
  name: myappbackend
  labels:
    app: myappbackend
    service: myappbackend
spec:
  selector:
    app: myappbackend
  ports:
    - port: 8000
      targetPort: 80
      name: http