apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  ConnectionString: 'server={{ .Release.Name }}-db-service;port=3306;user=root;password=password;'
  DbPassword: 'password'