###

GET http://172.21.54.219:32080

###

GET {{ proxy-app }}

###

GET http://172.21.54.219:32081?url=http://echoserver

###

GET http://172.21.54.219:32081?url=http://echoserver
X-AUTH-TOKEN: token

###

GET {{ proxy-app }}?url=http://echoserver/error?times=3
