---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app: myapp
    version: v1
spec:
  selector:
    matchLabels:
      app: myapp
      version: v1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      containers:
        - image: fenkss/express-health
          name: health
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
  labels:
    app: myapp
    version: v2
spec:
  selector:
    matchLabels:
      app: myapp
      version: v2
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
        - image: fenkss/express-health
          name: health
          ports:
            - containerPort: 8000