---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-backend
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: qqq-services
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger-operator
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
  labels:
    istio-injection: disabled
