---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    istio-injection: enabled