config:
  dbname: "otusdb"

backend:
  imagefirst: "lisitsynalex/myapp_backend:hw4-lecture10-v1"
  imagesecond: "lisitsynalex/myapp_backend:hw4-lecture10-v2"
  replicaCount: 1
  version: v1

migrator:
  image: "lisitsynalex/myapp_migrator:hw3-lecture9"

mysql:
  image: "mariadb:10.7.3"