apiVersion: v1
kind: Namespace
metadata:
  name: echo-istio
  labels:
    istio-injection: disabled # Включаем инжект сайдкаров Istio для неймспейса disabled

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echo-istio
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 8080
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-first
  namespace: echo-istio
  labels:
    app: echoserver
    version: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: "1"
  template:
    metadata:
      labels:
        app: echoserver
        version: "1"
    spec:
      containers:
        - name: echoserver
          image: escadockerhub/proxy-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-second
  namespace: echo-istio
  labels:
    app: echoserver
    version: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: "2"
  template:
    metadata:
      labels:
        app: echoserver
        version: "2"
    spec:
      containers:
        - name: echoserver
          image: escadockerhub/proxy-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080