apiVersion: batch/v1
kind: Job
metadata:
  name: load
  namespace: echo-istio
spec:
  template:
    metadata:
      labels:
        app: load
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
        - name: load
          image: escadockerhub/load-otus-demo:1.2
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 1