---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-np
  namespace: jaeger
  labels:
    app: jaeger
    app.kubernetes.io/component: service-query
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/part-of: jaeger
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: jaeger