---
apiVersion: v1
kind: Service
metadata:
  name: health-service
  namespace: health
  labels:
    app: health-app
spec:
  selector:
    app: health-app
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8000
      protocol: TCP
      targetPort: 8000
      name: api
