apiVersion: v1
kind: Service
metadata:
  name: otus-5-service
spec:
  type: NodePort
  selector:
    app: otus-5-app
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: web