apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    prometheus: prom-prometheus
  name: prom-prometheus-nodeport
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: prom-prometheus
  type: NodePort
