---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-np
  namespace: monitoring
  labels:
    app: grafana
    prometheus: prom-prometheus
spec:
  type: NodePort
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana