---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
  labels:
    app: app-service
    service: app-service
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8000
      nodePort: 32080
      targetPort: 8000
  selector:
    app: app-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-v1
  namespace: default
  labels:
    app: app-service
    version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-service
      version: "v1"
  template:
    metadata:
      labels:
        app: app-service
        version: "v1"
    spec:
      containers:
        - name: app-service
          image: strider2038/otus-hello-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-v2
  namespace: default
  labels:
    app: app-service
    version: v2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-service
      version: "v2"
  template:
    metadata:
      labels:
        app: app-service
        version: "v2"
    spec:
      containers:
        - name: app-service
          image: strider2038/otus-hello-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /ready
            initialDelaySeconds: 10
            periodSeconds: 5
