---
apiVersion: v1
kind: Namespace
metadata:
  name: otus-hw4-ns
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: otus-hw4-app
  namespace: otus-hw4-ns
  labels:
    app: otus-hw4-app
    service: otus-hw4-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
  selector:
    app: otus-hw4-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otus-hw4-app
  namespace: otus-hw4-ns
  labels:
    account: otus-hw4-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: otus-hw4-ns
  name: otus-hw4-app-v1
  labels:
    app: otus-hw4-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus-hw4-app
      version: v1
  template:
    metadata:
      labels:
        app: otus-hw4-app
        version: v1
    spec:
      serviceAccountName: otus-hw4-app
      containers:
        - name: otus-hw4-app
          image: geracimov/otus-hw4-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: otus-hw4-ns
  name: otus-hw4-app-v2
  labels:
    app: otus-hw4-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus-hw4-app
      version: v2
  template:
    metadata:
      labels:
        app: otus-hw4-app
        version: v2
    spec:
      serviceAccountName: otus-hw4-app
      containers:
        - name: otus-hw4-app
          image: geracimov/otus-hw4-app:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
---
