apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echoserver-destinationrule
  namespace: istio-backend
spec:
  host: echoserver
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2