---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: echoserver-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "echoserver.arch.homework"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver-virtual-service
spec:
  hosts:
  - echoserver.arch.homework
  gateways:
  - echoserver-gateway
  http:
  - route:
    - destination:
        host: echoserver.default.svc.cluster.local
        subset: version-1
      weight: 50
    - destination:
        host: echoserver.default.svc.cluster.local
        subset: version-2
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echoserver
spec:
  host: echoserver.default.svc.cluster.local
  subsets:
  - name: version-1
    labels:
      version: v1
  - name: version-2
    labels:
      version: v2