# Создать Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali

# Создать CRD, использующийся Kiali operator'ом, чтобы развернуть Kiali
---
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali
spec:
  deployment:
    image_version: "v1.33.1"
  istio_namespace: "istio-system"
  auth:
    strategy: "anonymous"
  external_services:
    istio:
      component_status:
        components:
          - app_label: istiod
            is_core: true
          - app_label: istio-ingressgateway
            is_core: false
          - app_label: istio-egressgateway
            is_core: false


# Создать NodePort для прямого доступа к web-интерфейсу
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiali
  name: kiali-nodeport
  namespace: kiali
spec:
  ports:
    - name: http
      port: 20001
      protocol: TCP
      targetPort: 20001
  selector:
    app: kiali
  type: NodePort
