apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apalyvoda
  name: echoserver-v1
  labels:
    app: echoserver
    version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: v1
  template:
    metadata:
      labels:
        app: echoserver
        version: v1
    spec:
      containers:
        - name: echoserver
          image: echoserver
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080