apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-v1
  namespace: otus-app
  labels:
    app: otus
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus
      version: v1
  template:
    metadata:
      labels:
        app: otus
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-v2
  namespace: otus-app
  labels:
    app: otus
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus
      version: v2
  template:
    metadata:
      labels:
        app: otus
        version: v2
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80