apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: otus-destinationrule
  namespace: otus-app
spec:
  host: otus-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2