---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: "1"
  template:
    metadata:
      labels:
        app: echoserver
        version: "1"
    spec:
      containers:
        - name: echoserver
          image: proxy-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver2
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: "2"
  template:
    metadata:
      labels:
        app: echoserver
        version: "2"
    spec:
      containers:
        - name: echoserver
          image: proxy-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
