apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw5-v1-deployment
  namespace: default
  labels:
    app: hw5
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw5
      version: v1
  template:
    metadata:
      labels:
        app: hw5
        version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw5-v2-deployment
  namespace: default
  labels:
    app: hw5
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw5
      version: v2
  template:
    metadata:
      labels:
        app: hw5
        version: v2
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80