apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echoservice-destinationrule
spec:
  host: echoserver
  subsets:
    - name: echoserver-v1
      labels:
        version: v1
    - name: echoserver-v2
      labels:
        version: v2