---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      #nodePort: 32080
      targetPort: 8080
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v1
  namespace: default
  labels:
    app: echoserver
    version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version:  v1
  template:
    metadata:
      labels:
        app: echoserver
        version:  v1
    spec:
      containers:
        - name: echoserver
          image: proxy-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v2
  namespace: default
  labels:
    app: echoserver
    version: v2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: v2
  template:
    metadata:
      labels:
        app: echoserver
        version: v2
    spec:
      containers:
        - name: echoserver
          image: proxy-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: echoserver-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: echoserver-destinationrule
  namespace: default
spec:
  host: echoserver
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echoserver-virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - echoserver-gateway
  http:
    - route:
        - destination:
            subset: v1
            host: echoserver
            port:
              number: 80
          weight: 50
        - destination:
            subset: v2
            host: echoserver
            port:
              number: 80
          weight: 50