---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 8000
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver1
  labels:
    app: echoserver
    version: v0.0.1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: v0.0.1
  template:
    metadata:
      labels:
        app: echoserver
        version: v0.0.1
    spec:
      containers:
        - name: echoserver
          image: nitrodenov/otus:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: container-port
              containerPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver2
  labels:
    app: echoserver
    version: v0.0.2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: v0.0.2
  template:
    metadata:
      labels:
        app: echoserver
        version: v0.0.2
    spec:
      containers:
        - name: echoserver
          image: nitrodenov/otus:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: container-port
              containerPort: 8000