---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  labels:
    app: echoserver
    service: echoserver
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 8080
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v1
  labels:
    app: echoserver
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
      version: v1
  template:
    metadata:
      labels:
        app: echoserver
        version: v1
    spec:
      containers:
        - name: echoserver
          image: exxbrain/echoserver
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v2
  labels:
    app: echoserver
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
      version: v2
  template:
    metadata:
      labels:
        app: echoserver
        version: v2
    spec:
      containers:
        - name: echoserver
          image: exxbrain/echoserver
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080