---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled # Включаем инжект сайдкаров Istio для неймспейса

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver2
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: "http"  # Istio требует явного указания протокола при определенных настройках
  selector:
    app: echoserver2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver2
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver2
      version: "1"
  template:
    metadata:
      labels:
        app: echoserver2
        version: "1"
    spec:
      containers:
        - name: echoserver2
          image: vndovr/proxy-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
