---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: echoserver-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - default/echoserver-gateway
  http:
    - route:
        - destination:
            host: echoserver
            subset: v1
          weight: 50
        - destination:
            host: echoserver
            subset: v2
          weight: 50
    - route:
        - destination:
            host: proxy-app
            subset: v1
          weight: 100

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echoserver
  namespace: default
spec:
  host: echoserver
  subsets:
    - name: v1
      labels:
        version: "1"
    - name: v2
      labels:
        version: "2"