apiVersion: batch/v1
kind: Job
metadata:
  name: load
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: load
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
        - name: load
          image: kpolyanichko/load-otus-demo:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 1