apiVersion: batch/v1
kind: Job
metadata:
  name: load
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: load
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
        - name: load
          image: load-otus-demo
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: "$HOST"
      restartPolicy: Never
  backoffLimit: 1