apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-app

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-app
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32081
      targetPort: 8080
      name: "http" # Istio требует явного указания протокола при определенных настройках
  selector:
    app: proxy-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-app
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: proxy-app
      version: "1"
  template:
    metadata:
      labels:
        app: proxy-app
        version: "1"
    spec:
      containers:
        - name: proxy-app
          image: rined/proxy-app:v0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
