apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hw5-destinationrule
  namespace: hw5
spec:
  host: hw5-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2