FROM nginx:alpine
RUN echo "server {\
    listen       80;\
    location / {\
        add_header Content-Type text/plain;\
        return 200 'Hello form v1';\
    }\
}\
" > /etc/nginx/conf.d/default.conf
