kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: echoserver-service
  namespace: default
  labels:
    kiali_wizard: weighted_routing
spec:
  hosts:
    - '*'
  gateways:
    - default/echoserver-service-gateway
  http:
    - route:
        - destination:
            host: echoserver.default.svc.cluster.local
            subset: v1
          weight: 50
        - destination:
            host: echoserver.default.svc.cluster.local
            subset: v2
          weight: 50

---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: echoserver-service
  namespace: default
  labels:
    kiali_wizard: weighted_routing
spec:
  host: echoserver.default.svc.cluster.local
  subsets:
    - labels:
        version: "1"
      name: v1
    - labels:
        version: "2"
      name: v2
---
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: echoserver-service-gateway
  labels:
    kiali_wizard: weighted_routing
spec:
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway