apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: echoserver-gw
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echoserver-rule
spec:
  host: echoserver
  subsets:
    - name: v1
      labels:
        version: "1"
    - name: v2
      labels:
        version: "2"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver-svc
spec:
  hosts:
    - "*"
  gateways:
    - echoserver-gw
  http:
    - route:
        - destination:
            host: echoserver
            subset: v1
          weight: 50
        - destination:
            host: echoserver
            subset: v2
          weight: 50