apiVersion: v1
kind: Namespace
metadata:
  name: otus-hw04-ns
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: enabled