apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
    DB_URL: jdbc:postgresql://homework3-db-postgresql.default.svc.cluster.local:5432/homework3
    DB_NAME: homework3
    DB_USER: test
    DB_PASSWORD: password
