apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
spec:
  selector:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
  ports:
    - protocol: TCP
      name: {{ .Values.app.service.name }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}