{{ $userId := .Values.postgresql.postgresqlUsername }}
{{ $password := .Values.postgresql.postgresqlPassword }}
{{ $dbServer := (include "eshop-chart.postgresqlFullname" . ) }}
{{ $port := .Values.postgresql.service.port }}
{{ $messageBroker := (include "message-broker.fullname" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eshop-chart.fullname" . }}
  labels:
    {{- include "eshop-chart.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  product-search-service-appsettings.secrets.json: |-
    {
      "ConnectionStrings": {
        "ProductDBConnection": "UserID={{ $userId }};Password={{ $password }};Server={{ $dbServer }};Port={{ $port }};Database={{ .Values.productSearchService.database }};Integrated Security=true;Pooling=true;"
      },
      "MassTransitConfig": {
        "Host": {{ $messageBroker | quote }},
        "VirtualHost": "/",
        "Username": {{ .Values.messageBroker.user | quote }},
        "Password": {{ .Values.messageBroker.password | quote }},
        "SSLActive": false,
        "SSLThumbprint": "a7a75205438e0b3697be97adc6ebbea715bf16b4"
      }
    }
  delivery-service-appsettings.secrets.json: |-
    {
      "ConnectionStrings": {
        "DeliveryDBConnection": "UserID={{ $userId }};Password={{ $password }};Server={{ $dbServer }};Port={{ $port }};Database={{ .Values.deliveryService.database }};Integrated Security=true;Pooling=true;"
      },
      "MassTransitConfig": {
        "Host": {{ $messageBroker | quote }},
        "VirtualHost": "/",
        "Username": {{ .Values.messageBroker.user | quote }},
        "Password": {{ .Values.messageBroker.password | quote }},
        "SSLActive": false,
        "SSLThumbprint": "a7a75205438e0b3697be97adc6ebbea715bf16b4"
      }
    }
  order-service-appsettings.secrets.json: |-
    {
      "ConnectionStrings": {
        "OrderDBConnection": "UserID={{ $userId }};Password={{ $password }};Server={{ $dbServer }};Port={{ $port }};Database={{ .Values.orderService.database }};Integrated Security=true;Pooling=true;"
      },
      "MassTransitConfig": {
        "Host": {{ $messageBroker | quote }},
        "VirtualHost": "/",
        "Username": {{ .Values.messageBroker.user | quote }},
        "Password": {{ .Values.messageBroker.password | quote }},
        "SSLActive": false,
        "SSLThumbprint": "a7a75205438e0b3697be97adc6ebbea715bf16b4"
      }
    }
  payment-service-appsettings.secrets.json: |-
    {
      "ConnectionStrings": {
        "PaymentDBConnection": "UserID={{ $userId }};Password={{ $password }};Server={{ $dbServer }};Port={{ $port }};Database={{ .Values.paymentService.database }};Integrated Security=true;Pooling=true;"
      },
      "MassTransitConfig": {
        "Host": {{ $messageBroker | quote }},
        "VirtualHost": "/",
        "Username": {{ .Values.messageBroker.user | quote }},
        "Password": {{ .Values.messageBroker.password | quote }},
        "SSLActive": false,
        "SSLThumbprint": "a7a75205438e0b3697be97adc6ebbea715bf16b4"
      }
    }
  warehouse-service-appsettings.secrets.json: |-
    {
      "ConnectionStrings": {
        "WarehouseDBConnection": "UserID={{ $userId }};Password={{ $password }};Server={{ $dbServer }};Port={{ $port }};Database={{ .Values.warehouseService.database }};Integrated Security=true;Pooling=true;"
      },
      "MassTransitConfig": {
        "Host": {{ $messageBroker | quote }},
        "VirtualHost": "/",
        "Username": {{ .Values.messageBroker.user | quote }},
        "Password": {{ .Values.messageBroker.password | quote }},
        "SSLActive": false,
        "SSLThumbprint": "a7a75205438e0b3697be97adc6ebbea715bf16b4"
      }
    }
  auth-server-appsettings.secrets.json: |-
    {
      "ConnectionStrings": {
        "IdentityServerDBConnection": "UserID={{ $userId }};Password={{ $password }};Server={{ $dbServer }};Port={{ $port }};Database={{ .Values.authServer.database }};Integrated Security=true;Pooling=true;"
      }
    }
  gateway-appsettings.secrets.json: |-
    {
      "AuthenticationProvider": {
        "Name": "identity_provider",
        "Url": "http://{{ include "auth-server.fullname" . }}:{{ .Values.service.port }}",
        "ClientId": "auth-api-gateway",
        "ClientSecret": "FBF6367F-B077-45FD-8F9D-429BB5926073",
        "ValidAudiences": "product-api; profile-api"
      }
    }  